version: '3.5'

services:
  db_mysql:
    image: mysql
    container_name: db-cusro-spring
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: curso-spring
      MYSQL_USER: curso-spring
      MYSQL_PASSWORD: curso-spring

  adminer:
    image: adminer
    ports:
    - 8090:8080

